[2024-11-22T16:51:40.678+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T16:51:40.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T15:08:00+00:00 [queued]>
[2024-11-22T16:51:40.712+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T15:08:00+00:00 [queued]>
[2024-11-22T16:51:40.713+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T16:51:40.730+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-22 15:08:00+00:00
[2024-11-22T16:51:40.740+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T16:51:40.741+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2024-11-22T16:51:40.740+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-22T15:08:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpq6v1h6_x']
[2024-11-22T16:51:40.742+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask load
[2024-11-22T16:51:40.759+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-22T16:51:40.792+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T15:08:00+00:00 [running]> on host 022fc877716c
[2024-11-22T16:51:40.866+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T15:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T15:08:00+00:00'
[2024-11-22T16:51:40.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T16:51:41.040+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T16:51:41.041+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 18, in load_data_to_postgres
    raise ValueError("Environment variable POSTGRES_DB is not set.")
ValueError: Environment variable POSTGRES_DB is not set.
[2024-11-22T16:51:41.054+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-22T15:08:00+00:00, execution_date=20241122T150800, start_date=20241122T165140, end_date=20241122T165141
[2024-11-22T16:51:41.066+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task load (Environment variable POSTGRES_DB is not set.; 193)
[2024-11-22T16:51:41.075+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T16:51:41.091+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T16:51:41.100+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
