[2024-11-22T19:08:04.210+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T19:08:04.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T03:00:00+00:00 [queued]>
[2024-11-22T19:08:04.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T03:00:00+00:00 [queued]>
[2024-11-22T19:08:04.293+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T19:08:04.362+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-22 03:00:00+00:00
[2024-11-22T19:08:04.382+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=276) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T19:08:04.387+0000] {standard_task_runner.py:63} INFO - Started process 304 to run task
[2024-11-22T19:08:04.383+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-22T03:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp88rv_4ml']
[2024-11-22T19:08:04.390+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask load
[2024-11-22T19:08:04.508+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-22T19:08:04.575+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T03:00:00+00:00 [running]> on host 785a755623b8
[2024-11-22T19:08:04.779+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T03:00:00+00:00'
[2024-11-22T19:08:04.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T19:08:05.237+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-22T19:08:05.239+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-22T19:08:05.240+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T19:08:05.257+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-22T03:00:00+00:00, execution_date=20241122T030000, start_date=20241122T190804, end_date=20241122T190805
[2024-11-22T19:08:05.389+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-22T19:08:05.416+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T19:08:05.428+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
