[2024-11-22T19:08:04.208+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T19:08:04.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load manual__2024-11-22T19:07:55.658671+00:00 [queued]>
[2024-11-22T19:08:04.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load manual__2024-11-22T19:07:55.658671+00:00 [queued]>
[2024-11-22T19:08:04.293+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T19:08:04.362+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-22 19:07:55.658671+00:00
[2024-11-22T19:08:04.382+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T19:08:04.383+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'manual__2024-11-22T19:07:55.658671+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpoopl7yb7']
[2024-11-22T19:08:04.387+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-11-22T19:08:04.388+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load
[2024-11-22T19:08:04.503+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-22T19:08:04.575+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load manual__2024-11-22T19:07:55.658671+00:00 [running]> on host 785a755623b8
[2024-11-22T19:08:04.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T19:07:55.658671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T19:07:55.658671+00:00'
[2024-11-22T19:08:04.786+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T19:08:05.246+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-22T19:08:05.247+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-22T19:08:05.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T19:08:05.262+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=manual__2024-11-22T19:07:55.658671+00:00, execution_date=20241122T190755, start_date=20241122T190804, end_date=20241122T190805
[2024-11-22T19:08:05.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-22T19:08:05.415+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T19:08:05.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
