[2024-11-22T19:08:04.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T19:08:04.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-22T19:08:04.302+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-22T19:08:04.315+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T19:08:04.421+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-22 00:00:00+00:00
[2024-11-22T19:08:04.435+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T19:08:04.438+0000] {standard_task_runner.py:63} INFO - Started process 308 to run task
[2024-11-22T19:08:04.437+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpdmoo3klx']
[2024-11-22T19:08:04.441+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask load
[2024-11-22T19:08:04.565+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-22T19:08:04.638+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-22T00:00:00+00:00 [running]> on host 785a755623b8
[2024-11-22T19:08:04.844+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-22T19:08:04.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T19:08:05.469+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-22T19:08:05.471+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-22T19:08:05.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T19:08:05.504+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241122T190804, end_date=20241122T190805
[2024-11-22T19:08:05.605+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-22T19:08:05.632+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T19:08:05.708+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
